    LIST	p=16f887
    #INCLUDE	<p16f887.inc>

    ; Variables externas
CONT    EQU 0x20
WTEMP   EQU 0X70
STATUST EQU 0X71

    ;PARTE PRINCIPAL
    ORG 0X0
    GOTO    MAIN
    
    ; DIRECCION DE INTERRUPCIONES
    ORG 0X04
    GOTO    IRS


    ORG 0X05
MAIN:
    ;CONFIGURACIONES BASICAS
    BANKSEL PIE1
    MOVLW   B'01110000' ;HABILITO INTERRUPCION POR ADC, RECEPCION Y TRANSMICION
    MOVWF   PIE1
    CLRF    PIR1
    MOVLW   B'110000000'    ;HABILITO GIE Y PEIE - CORROBORAR SI ESTAN EN EL MISMO BANCO
    MOVWF   INTCON

MAIN_LOOP:  ;LOOP PRINCIPAL
    NOP
    GOTO    MAIN_LOOP
    
    
; Seccion de interrupciones
IRS:
    ;GUARDADO DE CONTEXTO
    MOVWF   WTEMP
    SWAPF   STATUS,W
    MOVWF   STATUST

    BANKSEL PIR1
    ;TESTEO DE BANDERAS LEVANTADAS
    BTFSC   PIR1,ADIF   ;BANDERA DEL ADC
    GOTO    ISR_ADC
    BTFSC   PIR1,RCIF   ;BANDERA DE RECEPCION MODULO EUSART
    GOTO    ISR_RECEPCION
    BTFSC   PIR1,TXIF   ;BANDERA DE TRANSMICION MODULO EUSART
    GOTO    ISR_TRANSMICION 
    GOTO    SALIR

;   RUTINA DE INTERRUPCION ADC
ISR_ADC:
    NOP
    GOTO    SALIR

;   RUTINA DE INTERRUPCION RECEPCION EUSART
ISR_RECEPCION:
    NOP
    GOTO    SALIR

ISR_TRANSMICION:
    NOP
    GOTO    SALIR



SALIR    ;RECUPERACION DE CONTEXTO, LIMPIEZA DE BANDERA Y SALIDA
    SWAPF   STATUST,W
    MOVWF   STATUST
    SWAPF   WTEMP,F
    SWAPF   WTEM,W
    RETFIE

    
    
    END