    LIST	p=16f887
    #INCLUDE	<p16f887.inc>

    ; Variables externas
INGRESAR    EQU 0x20    ;VARIABLE QUE NOS DICE SI ESTAMOS ESPERANDO UN NUMERO
                        ;B0 = 1 = ESPERANDO - B0 = 0 = NO ESPERANDO
WTEMP   EQU 0X70
STATUST EQU 0X71

    ;PARTE PRINCIPAL
    ORG     0X0
    GOTO    MAIN
    
    ; DIRECCION DE INTERRUPCIONES
    ORG     0X04
    GOTO    ISR


    ORG 0X05
MAIN:
    CLRF        INGRESAR     ;LIMPIO BANDERA DE INGRESAR NUMERO
    ;PUERTOS
    BANKSEL     TRISD
    MOVLW       B'11110000' ;RD7-RD4 ENTRADA / RD3-RD0 SALIDA PARA LECTURA DE TECLADO
    MOVWF       TRISD
    MOVLW       B'00000001' ;RB0 ENTRRADA DEL PULSADOR - RB1 Y RB2 SALIDAS A LOS DISPLAY
    MOVWF       TRISB
    BANKSEL     ANSELH
    BCF         ANSELH,ANS12 ;RB0 COMO DIGITAL

    ;OSCILADOR INTERNO
    BANKSEL     OSCCON
    MOVLW       B'01011000'  ;OSCILADOR INTERNO DE 2MHz
    MOVWF       OSCCON

    ;ADC

    ;TRANSMICION

    ;TMR1
    BANKSEL     T1CON
    CLF         TMR1L
    CLF         TMR1H
    MOVLW       B'00110000'
    MOVWF       T1CON

    ;INTERRUPCIONES
    BANKSEL     INTCON 
    MOVLW       B'11010000' ;HABILITO GIE - PEIE - INTE Y LIMPIO BANDERA INTF
    MOVWF       INTCON 
    BCF         PIR1,ADIF
    BCF         PIR1,TXIF
    BCF         PIR1,TMR1IF
    BANKSEL     OPTION_REG
    BCF         OPTION_REG,INTEDG   ;FLANCO DE BAJADA PARA INT - PULSADOR EN PULL-UP
    MOVLW       B'01010001' ;HABILITO INTERRUPCION POR ADC - TRANSMICION - TMR1

    ;ACTIVADO DEL TMR1
    BANKSEL     T1CON
    BSF         T1CON,0 ;ACTIVO EL TMR1

MAIN_LOOP:  ;LOOP PRINCIPAL
    NOP
    GOTO    MAIN_LOOP
    
    
; RUTINA DE SERVICIO A LA INTERRUPCION
ISR:    
    ;GUARDADO DE CONTEXTO
    MOVWF   WTEMP
    SWAPF   STATUS,W
    MOVWF   STATUST

    BANKSEL PIR1

    ;TESTEO DE BANDERAS LEVANTADAS
    BTFSC   PIR1,ADIF   ;BANDERA DEL ADC
    GOTO    ISR_ADC
    BTFSC   PIR1,TXIF   ;BANDERA DE TRANSMICION MODULO EUSART
    GOTO    ISR_TRANSMICION 
    GOTO    SALIR

;   RUTINA DE INTERRUPCION ADC
ISR_ADC:
    NOP
    BCF     PIR1,ADIF   
    GOTO    SALIR

;   RUTINA DE INTERRUPCION RECEPCION EUSART


ISR_TRANSMICION:
    NOP
    BCF     PIR1,TXIF
    GOTO    SALIR


SALIR    ;RECUPERACION DE CONTEXTO, LIMPIEZA DE BANDERA Y SALIDA
    SWAPF   STATUST,W
    MOVWF   STATUST
    SWAPF   WTEMP,F
    SWAPF   WTEM,W
    RETFIE

    
    
    END